src/Entity/Forum.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
/**
 * @ORM\Entity(repositoryClass="App\Repository\ForumRepository")
 * 
 * @author Lucas Santos <devlostpublisher@gmail.com>
 * 
 * @todo Forum permissions 
 * @see https://symfony.com/doc/current/security.html#security-role-hierarchy
 * @see https://symfony.com/doc/current/security/voters.html
 */
class Forum
{
    /**
     * @var int
     * 
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * 
     * @ORM\Column(type="string", nullable=false)
     */
    private $name;

    /**
     * @var string
     * 
     * @ORM\Column(type="string", unique=true)
     */
    private $slug;

    /**
     * @var string
     * 
     * @ORM\Column(type="string", nullable=true)    
     */
    private $description;

    /**
     * @var string
     * 
     * @ORM\OneToMany(targetEntity="App\Entity\Thread", mappedBy="forum")
     */
    private $threads;

    /**
     * @var Thread
     * 
     * @ORM\OneToOne(targetEntity="App\Entity\Thread")
     * @ORM\JoinColumn(nullable=true)
     */
    private $last_thread;

    /**
     * @var Forum
     * 
     * @ORM\ManyToOne(targetEntity="Forum", inversedBy="children")
     */
    private $parent;

    /**
     * @var Forum[]|ArrayCollection
     * 
     * @ORM\OneToMany(targetEntity="Forum", mappedBy="parent")
     */
    private $children;

    /**
     * @var \DateTime
     * 
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /** 
    * @var bool
    *
    * @ORM\Column(type="boolean")
    */
    private $published = true; 

    public function __construct()
    {
        $this->threads = new ArrayCollection();
        $this->children = new ArrayCollection();
        $created_at = new \DateTime();
    }

    public function getParents(){
        $temp = [];
        while($this->parent){
            $temp[] = $this->parent->slug;
        }

        return $temp;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getName(): ?string
    {
        return $this->name;        
    }

    public function setSlug(String $slug): void
    {
        $this->slug = $slug;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function getThreads(): ?Collection
    {
        return $this->threads;
    }

    public function setLastThread(Thread $thread): void
    {
        $this->last_thread = $thread;
    }

    public function getLastThread(): ?Thread
    {
        return $this->last_thread;
    }

    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setParent(Forum $parent): void
    {
        $this->parent = $parent;
    }

    public function getParent(): ?Forum
    {
        return $this->parent;
    }

    public function setCreatedAt(\DateTime $created_at): void
    {
        $this->created_at = $created_at;
    }

    public function getCreatedAt(): \DateTime
    {
        return $this->created_at;
    }

    public function getChildren(): ?Collection
    {
        return $this->children;
    }

    public function isPublished(): bool
    {
        return $this->published;
    }

    public function setPublished(bool $value): void
    {
        $this->published = $value;
    }
}

src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 * 
 * @author Lucas Santos <devlostpublisher@gmail.com>
 */
class Post
{
    /**
     * @var int
     * 
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var User
     * 
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="posts")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=false)
     */
    private $user;

    /**
     * @var Thread
     * 
     * @ORM\ManyToOne(targetEntity="App\Entity\Thread", inversedBy="posts")
     * @ORM\JoinColumn(name="thread_id", referencedColumnName="id", nullable=false)
     */
    private $thread;

    /**
     * @var string
     * 
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @var Status
     * 
     * @ORM\ManyToOne(targetEntity="App\Entity\Status")   
    */
    private $status;

    /**
     * @var int
     * 
     * @ORM\Column(type="integer")
     */
    private $reported = 0;

    /**
     * @var \DateTime
     * 
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct(){
        $this->created_at = new \DateTime();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function setUser(User $user): void
    {
        $this->user = $user;
    }

    public function getUser(): User
    {
        return $this->user;
    }

    public function setThread(Thread $thread): void
    {
        $this->thread = $thread;
    }

    public function getThread(): Thread
    {
        return $this->thread;
    }

    public function setContent(string $content): void
    {
        $this->content = $content;
    }

    public function getContent(): string
    {
        return $this->content;        
    }

    public function setCreatedAt(\DateTime $created_at): void
    {
        $this->created_at = $created_at;
    }

    public function getCreatedAt(): \DateTime
    {
        return $this->created_at;
    }

    public function setStatus(Status $status): void
    {
        $this->status = $status;
    }

    public function getStatus(): Status
    {
        return $this>status;
    }

    public function getReported(): int
    {
        return $this->reported;
    }

    public function addReported(int $value): void
    {
        $this->reported += $value;
    }
}

src/Entity/Thread.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
/**
 * @ORM\Entity(repositoryClass="App\Repository\ThreadRepository")
 * 
 * @author Lucas Santos <devlostpublisher@gmail.com>
 */
class Thread
{
    /**
     * @var int
     * 
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * 
     * @ORM\Column(type="string")
     */
    private $subject;

    /**
     * @var Status
     * 
     * @ORM\ManyToOne(targetEntity="App\Entity\Status")
     */
    private $status;

    /**
     * @var int
     * 
     * @ORM\Column(type="integer")
     */
    private $reported = 0;

    /**
     * @var \DateTime
     * 
     * @ORM\Column(type="datetime")
     */
    private $created_at;
   
    /**
     * @var User
     * 
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="threads")
     */
    private $user;
    
    /**
     * @var Forum
     * 
     * @ORM\ManyToOne(targetEntity="App\Entity\Forum", inversedBy="threads")
     */
    private $forum;

    /**
     * @var Post[]|ArrayCollection
     * 
     * @ORM\OneToMany(targetEntity="App\Entity\Post", mappedBy="thread")
     */
    private $posts;

    /**
     * @var Post
     * 
     * @ORM\OneToOne(targetEntity="App\Entity\Post")
     */
    private $last_post;

    /**
     * @var bool
     * 
     * @ORM\Column(type="boolean")
     */
    private $closed = false;

    /**
     * @var int
     * 
     * @ORM\Column(type="integer")
     */
    private $views = 0;
    
    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->created_at = new \DateTime();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function setSubject(string $subject): void 
    {
        $this->subject = $subject;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setStatus(Status $status): void
    {
        $this->status = $status;
    }

    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setCreatedAt(\DateTime $created_at): void
    {
        $this->created_at = $created_at;
    }

    public function getCreatedAt(): \DateTime
    {
        return $this->created_at;
    }

    public function setUser(User $user): void
    {
        $this->user = $user;
    }

    public function getUser(): User
    {
        return $this->user;
    }

    public function setForum(Forum $forum): void
    {
        $this->forum = $forum;
    }

    public function getForum(): Forum
    {
        return $this->forum;
    }

    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function setLastPost(Post $last_post): void
    {
        $this->last_post = $last_post;
    }

    public function getLastPost(): ?Post
    {
        return $this->last_post;
    }

    public function isClosed(): bool
    {
        return $this->closed;
    }

    public function close(): void
    {
        $this->closed = true;
    }

    public function open(): void
    {
        $this->closed = false;
    }

    public function getViews(): bool
    {
        return $this->views;
    }

    public function addViews(int $ammount = 1): void
    {
        $this->views += $ammount;
    }

    public function getReported(): int
    {
        return $this->reported;
    }

    public function addReported(int $value): void
    {
        $this->reported += $value;
    }
}

templates/includes/_forum_table.html.twig
<table class="table table-sm">
    <thead class="thead-dark">
        {% if threads | length %}
        <th>Threads in {{ threads[0].forum.name }}</th>
        {% else %}
        <th>Threads</th>
        {% endif %}
        <th>Posts</th>
        <th>Start date</th>
        <th>Last Post</th>
        {% if is_granted('ROLE_MODERATOR') %}
        <th>Actions</th>
        {% endif %}
        <th></th>
    </thead>
    <tbody>
    {% for thread in threads %}
        <tr>
            <td><a href="{{ path('thread_show', {slug: thread.forum.slug, id: thread.id}) }}">{{ thread.subject }}</a> by: {{ thread.user.username }}</td>
            <td>{{ thread.posts.count() }}</td>
            <td>{{ thread.createdat | date() }}</td>
            <td>                        
                <a href="{{ path('user_show', {id: thread.lastPost.user.id}) }}">
                    {{ thread.lastPost.user.username | default  }}
                </a> {{ thread.lastPost.createdAt | date }}</td>
            {% if is_granted('ROLE_MODERATOR') %}
                <td>
                    <a href="http://">
                        <i class="fas fa-pencil-alt fa-lg" title="edit post"></i>                    
                    </a>
                    <a href="http://">
                        <i class="fas fa-trash-alt fa-lg" title="delete post"></i>                    
                    </a>
                    <a href="http://">
                        <i class="fas fa-lock fa-lg" alt="close"></i>                    
                    </a>
                </td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/includes/_forums_table.html.twig
<table class="table table-sm">
    <thead class="thead-dark">
        <th>Forum</th>
        <th>Threads</th>
        <th>Last Update</th>
    </thead>
    <tbody>
        {% for forum in forums %}
        <tr>
            <td>
                <div class="row">
                    <div class="col-md-6 col-lg-4 col-12">
                        <a href="{{ path( 'forum_show', {slug: forum.slug } ) }}"><h5>{{ forum.name }}</h5></a>
                        {{ forum.description }} 
                    </div>
                    {%if is_granted('ROLE_MODERATOR') %}
                        <div class="col-md-6 col-lg-8 col-6">
                            <a href="{{ path('forum_settings', { slug: forum.slug }) }}">
                                <i class="fas fa-cog fa-lg" title="forum settings"></i>
                            </a>
                        </div>
                    {% endif %}
                </div>
            </td>
            <td>{{ forum.threads | length }}</td>
            <td>
                {% if forum.lastThread %}
                <a href="{{ path('thread_show', {slug: forum.slug, id: forum.lastThread.id})}}">
                    {{ forum.lastThread.subject | default }}
                </a> 
                <br>
                by 
                <a href="{{ path('user_show', {id: forum.lastThread.user.id}) | default }}">
                    {{ forum.lastThread.lastPost.user.username | default  }}
                </a> {{ forum.lastThread.lastPost.createdAt | date }}
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/includes/_thread_table.html.twig
<table class="table table-sm">
    <thead class="thead-dark">
        <th>{{ thread.subject }}</th>
        {% if is_granted('ROLE_MODERATOR') %}
        <th>
            <a href="http://">
                <i class="fas fa-pencil-alt fa-lg" title="edit post"></i>                    
            </a>
            <a href="http://">
                <i class="fas fa-trash-alt fa-lg" title="delete post"></i>                    
            </a>
            <a href="http://">
                <i class="fas fa-lock fa-lg" title="close post"></i>                    
            </a>
        </th>
        {% endif %}
    </thead>
    <tbody>
        {% for post in thread.posts %}
            <tr>
                <td>
                    <small>{{ post.user.username }} {{ post.createdat | date() }}</small>
                    <p id="post_{{ post.id }}">{{post.content}}</p>
                    {% if is_granted('ROLE_USER') %}
                        <a id="{{ post.id }}" class="btn btn-sm btn-secondary" href="#"
                            onclick="reply(this)"
                        >reply</a>
                        {%if (app.user and app.user.username == post.user.username) or is_granted('ROLE_MODERATOR') %}
                            <a class="btn btn-sm btn-secondary" href="#">edit</a>
                            <a href="{{ path('post_delete', { id : post.id }) }}" class="btn btn-sm btn-secondary">remove</a>                            
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        <tr>
            <td>
            {% if is_granted('ROLE_USER') %}
                {{ form_start(form) }}
                <div class="form-group">
                    {{ form_label(form.content) }}
                    {{ form_errors(form.content) }}
                    {{ form_widget(form.content, { 'attr': {'class': 'form-control' }}) }}
                </div>
                {{ form_widget(form.submit, { 'attr': {'class': 'btn btn-secondary' }}) }}
                {{ form_end(form) }}
            {% else %}
                <a href="{{ path('login') }}">Login</a> to post a new reply
            {% endif %}
            </td>
        </tr>
    </tbody>
</table>
{% block javascripts %}
    <script>
        function reply(e){
            post = document.getElementById('post_'+e.id);
            console.log('post_'+e.id)
            post_content = document.getElementById('post_content');
            post_content.textContent = post.textContent;
        }
    </script>
{% endblock %}